# Generated by Django 6.0 on 2025-12-25 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='DateCreation',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='adresse',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='derniere_modification',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='etatCompte',
            field=models.CharField(choices=[('A', 'Active'), ('D', 'Desactive')], default='A', max_length=100),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='heure_derniere_modification',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='numero_tel',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='privilege',
            field=models.CharField(choices=[('C', 'Client'), ('AD', 'Administrateur')], default='C', max_length=100),
        ),
    ]
